app <- ShinyDriver$new("../")
app$snapshotInit("mytest")

app$snapshot()
app$uploadFile(file1 = "~/Documents/COGS_cognition_paper/Data/Paper_results/COGS_IQ_pathway_PRS_analysis_run_2_update_25-07-2018_at_08.35.txt") # <-- This should be the path to the file, relative to the app's tests/ directory
app$snapshot()
app$setInputs(Gene_regions = c("extended", "Full"))
app$snapshot()
app$setInputs(DSM = "broad")
app$snapshot()
app$setInputs(geneset = c("abnormal_grooming_behavior", "abnormal_behavior", "abnormal_behavioral_response_to_xenobiotic", "abnormal_neuron_differentiation", "Lek2015_LoFintolerant_90", "abnormal_nervous_system_electrophysiology", "abnormal_long_term_potentiation", "Cav2_channels", "FMRP_targets", "whole_genome"))
app$setInputs(geneset = c("abnormal_grooming_behavior", "abnormal_behavioral_response_to_xenobiotic", "abnormal_neuron_differentiation", "Lek2015_LoFintolerant_90", "abnormal_nervous_system_electrophysiology", "abnormal_long_term_potentiation", "Cav2_channels", "FMRP_targets", "whole_genome"))
app$setInputs(geneset = c("abnormal_grooming_behavior", "abnormal_neuron_differentiation", "Lek2015_LoFintolerant_90", "abnormal_nervous_system_electrophysiology", "abnormal_long_term_potentiation", "Cav2_channels", "FMRP_targets", "whole_genome"))
app$snapshot()
app$snapshot()
app$setInputs(geneset = c("abnormal_grooming_behavior", "Lek2015_LoFintolerant_90", "abnormal_nervous_system_electrophysiology", "abnormal_long_term_potentiation", "Cav2_channels", "FMRP_targets", "whole_genome"))
app$setInputs(geneset = c("abnormal_grooming_behavior", "abnormal_nervous_system_electrophysiology", "abnormal_long_term_potentiation", "Cav2_channels", "FMRP_targets", "whole_genome"))
app$setInputs(geneset = c("abnormal_grooming_behavior", "abnormal_long_term_potentiation", "Cav2_channels", "FMRP_targets", "whole_genome"))
app$snapshot()
app$snapshot()
app$snapshot()
app$setInputs(plotHeight = 166)
app$setInputs(Significance_threshold = c("1e-06", "1e-04", "0.01", "0.05", "0.1", "0.2", "0.5", "1"))
app$setInputs(Significance_threshold = c("1e-04", "0.01", "0.05", "0.1", "0.2", "0.5", "1"))
app$setInputs(Significance_threshold = c("0.01", "0.05", "0.1", "0.2", "0.5", "1"))
app$snapshot()
app$setInputs(Significance_threshold = c("1e-04", "0.01", "0.05", "0.1", "0.2", "0.5", "1"))
app$snapshot()
app$setInputs(Significance_threshold = c("1e-06", "1e-04", "0.01", "0.05", "0.1", "0.2", "0.5", "1"))
app$snapshot()
app$setInputs(Significance_threshold = c("5e-08", "1e-06", "1e-04", "0.01", "0.05", "0.1", "0.2", "0.5", "1"))
app$snapshot()
